// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHRhMo6KEuFGR-3QdVPzh2L1U-zXgwLsY',
    appId: '1:579927974676:web:53fd3eacaec0ccc9089801',
    messagingSenderId: '579927974676',
    projectId: 'ecofood-dec54',
    authDomain: 'ecofood-dec54.firebaseapp.com',
    storageBucket: 'ecofood-dec54.firebasestorage.app',
    measurementId: 'G-3KXTRQWFY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCv1Gb8GNbFbo76BtDOB7II0w4mq9NYyo',
    appId: '1:579927974676:android:a4593747fd3a19d8089801',
    messagingSenderId: '579927974676',
    projectId: 'ecofood-dec54',
    storageBucket: 'ecofood-dec54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLryt_bfxeu_lcJOe4XBG5BEHoGKBOOqQ',
    appId: '1:579927974676:ios:7862a1bb46a8dade089801',
    messagingSenderId: '579927974676',
    projectId: 'ecofood-dec54',
    storageBucket: 'ecofood-dec54.firebasestorage.app',
    iosClientId: '579927974676-i7plgt3514k4tab7dl3ltbrji26f8i51.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecofood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLryt_bfxeu_lcJOe4XBG5BEHoGKBOOqQ',
    appId: '1:579927974676:ios:7862a1bb46a8dade089801',
    messagingSenderId: '579927974676',
    projectId: 'ecofood-dec54',
    storageBucket: 'ecofood-dec54.firebasestorage.app',
    iosClientId: '579927974676-i7plgt3514k4tab7dl3ltbrji26f8i51.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecofood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHRhMo6KEuFGR-3QdVPzh2L1U-zXgwLsY',
    appId: '1:579927974676:web:6eb1e715102f6dd7089801',
    messagingSenderId: '579927974676',
    projectId: 'ecofood-dec54',
    authDomain: 'ecofood-dec54.firebaseapp.com',
    storageBucket: 'ecofood-dec54.firebasestorage.app',
    measurementId: 'G-17G0GH8594',
  );
}
